import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {JSDOM} from "jsdom";
import {indexedDB,IDBKeyRange} from "fake-indexeddb";
const root=path.resolve(import.meta.dirname,"..");
const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let n=0;const check=(message,value)=>{assert.ok(value,message);n++};
const dom=new JSDOM('<!doctype html><body><div id="root"><div class="shell"><aside><nav><button class="nav-exit">종료</button></nav></aside><main><div class="smart-command-grid"></div><div class="all-menu-grid"></div></main></div></div></body>',{runScripts:"outside-only",pretendToBeVisual:true});
Object.defineProperty(dom.window,"indexedDB",{value:indexedDB});
Object.defineProperty(dom.window,"IDBKeyRange",{value:IDBKeyRange});
dom.window.confirm=()=>true;
dom.window.requestAnimationFrame=callback=>dom.window.setTimeout(callback,0);
dom.window.eval(read("app/src/main/assets/smart-scheduler-v48.js"));
await wait(30);
check("사이드 예약 독립메뉴",!!dom.window.document.querySelector("aside .nav-scheduler"));
check("전체메뉴 예약 독립카드",!!dom.window.document.querySelector(".smart-scheduler-menu-card"));
check("홈 예약요약 미표시",!dom.window.document.querySelector(".smart-schedule-summary"));
dom.window.document.querySelector(".nav-scheduler").click();
await wait(40);
check("예약 선택 시 화면 표시",dom.window.document.querySelector(".smart-scheduler-backdrop").classList.contains("open"));
check("예약 외 화면 차단상태",dom.window.document.body.classList.contains("smart-scheduler-open"));
check("예약 메뉴 선택표시",dom.window.document.querySelector(".nav-scheduler").classList.contains("active"));
dom.window.document.querySelector(".smart-scheduler-close").click();
check("목록 복귀",!dom.window.document.body.classList.contains("smart-scheduler-open"));
check("예약 메뉴 선택해제",!dom.window.document.querySelector(".nav-scheduler").classList.contains("active"));
dom.window.document.getElementById("root").innerHTML='<button class="header-cattle-edit">개체정보 수정</button><nav class="cattle-detail-quicknav"></nav><section class="cattle-detail-page"><div class="cattle-resume-card">기본정보</div><div class="detail-heading">종합정보</div></section>';
dom.window.eval(read("app/src/main/assets/screen-isolation-v49.js"));
await wait(30);
check("개체상세 단독상태",dom.window.document.body.classList.contains("r49-cattle-detail-only"));
check("기본정보 편집명",dom.window.document.querySelector(".header-cattle-edit").textContent==="기본정보 수정·편집");
dom.window.document.getElementById("root").innerHTML='<div class="cattle-page-nav">다른 개체화면</div><section class="panel"><div class="bulk-selection-toolbar"><button class="bulk-delete-button">선택 개체 일괄삭제</button></div></section>';
await wait(30);
check("개체목록 단독상태",dom.window.document.body.classList.contains("r49-cattle-list-only"));
check("선택개체 삭제명",dom.window.document.querySelector(".bulk-delete-button").textContent==="선택개체 삭제");
dom.window.close();
console.log(`PASS: 메뉴·예약·개체화면 UI ${n}항목`);
